/**
 * Schema Validation Tests
 *
 * These tests verify that the configs generated by each client
 * conform to the canonical schemas defined in @gleanwork/mcp-config-schema.
 */

import { describe, it, expect } from 'vitest';
import { validateGeneratedConfig, CLIENT } from '@gleanwork/mcp-config';
import type { ConfigureOptions } from '../../configure/index.js';

import claudeCodeClient from '../../configure/client/claude-code.js';
import claudeDesktopClient from '../../configure/client/claude-desktop.js';
import codexClient from '../../configure/client/codex.js';
import cursorClient from '../../configure/client/cursor.js';
import gooseClient from '../../configure/client/goose.js';
import jetbrainsClient from '../../configure/client/jetbrains.js';
import junieClient from '../../configure/client/junie.js';
import vscodeClient from '../../configure/client/vscode.js';
import windsurfClient from '../../configure/client/windsurf.js';

describe('Schema Validation', () => {
  const clients = [
    { name: 'claude-code', client: claudeCodeClient, clientId: CLIENT.CLAUDE_CODE },
    { name: 'claude-desktop', client: claudeDesktopClient, clientId: CLIENT.CLAUDE_DESKTOP },
    { name: 'codex', client: codexClient, clientId: CLIENT.CODEX },
    { name: 'cursor', client: cursorClient, clientId: CLIENT.CURSOR },
    { name: 'goose', client: gooseClient, clientId: CLIENT.GOOSE },
    { name: 'jetbrains', client: jetbrainsClient, clientId: CLIENT.JETBRAINS },
    { name: 'junie', client: junieClient, clientId: CLIENT.JUNIE },
    { name: 'vscode', client: vscodeClient, clientId: CLIENT.VSCODE },
    { name: 'windsurf', client: windsurfClient, clientId: CLIENT.WINDSURF },
  ];

  describe('stdio transport (local)', () => {
    it.each(clients)(
      '$name: generates valid schema-conforming config',
      ({ client, clientId }) => {
        const config = client.configTemplate('test-instance', 'test-token');
        const result = validateGeneratedConfig(config, clientId);

        if (!result.success) {
          console.error(`${clientId} stdio validation errors:`, JSON.stringify(result.error?.issues, null, 2));
          console.error(`${clientId} stdio config:`, JSON.stringify(config, null, 2));
        }
        expect(result.success).toBe(true);
      },
    );
  });

  describe('http transport (remote)', () => {
    it.each(clients)(
      '$name: generates valid schema-conforming config',
      ({ client, clientId }) => {
        const options: ConfigureOptions = { remote: true };
        const config = client.configTemplate(
          'https://example-instance-be.glean.com/mcp/default',
          'test-token',
          options,
        );
        const result = validateGeneratedConfig(config, clientId);

        if (!result.success) {
          console.error(`${clientId} http validation errors:`, JSON.stringify(result.error?.issues, null, 2));
          console.error(`${clientId} http config:`, JSON.stringify(config, null, 2));
        }
        expect(result.success).toBe(true);
      },
    );
  });

  describe('http transport without token (OAuth/DCR)', () => {
    it.each(clients)(
      '$name: generates valid schema-conforming config without token',
      ({ client, clientId }) => {
        const options: ConfigureOptions = { remote: true };
        const config = client.configTemplate(
          'https://example-instance-be.glean.com/mcp/default',
          undefined, // No token - OAuth/DCR flow
          options,
        );
        const result = validateGeneratedConfig(config, clientId);

        if (!result.success) {
          console.error(`${clientId} no-token validation errors:`, JSON.stringify(result.error?.issues, null, 2));
          console.error(`${clientId} no-token config:`, JSON.stringify(config, null, 2));
        }
        expect(result.success).toBe(true);
      },
    );
  });

});
